CREATE DATABASE  IF NOT EXISTS `csit314`;
USE `csit314`;
/*
DROP TABLE IF EXISTS ;
CREATE TABLE (

    
);
*/

DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
  ACCID INT(11) NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL,
  PW VARCHAR(50) NOT NULL,
  ACCTYPE VARCHAR(50) NOT NULL,
  FIRSTNAME VARCHAR(50) NOT NULL,
  LASTNAME VARCHAR(50) NOT NULL,
  AGE INT(3) NOT NULL,
  PRIMARY KEY (ID)
);
/*
DROP TABLE IF EXISTS CINEMAHALL;
CREATE TABLE CINEMAHALL (

    
);

DROP TABLE IF EXISTS PURCHASES;
CREATE TABLE TICPURCHASES(
    QUANTITY
    PURCHASETYPE
    ITEM
    
    
);

DROP TABLE IF EXISTS ;
CREATE TABLE (

    
);
*/
